# -*- mode: ruby -*-
# vi: set ft=ruby :
MACHINES = {
  # VM name "homework1"
  :"homework1" => {
              # VM box
              :box_name => "centosHW",
              # VM CPU count
              :cpus => 2,
              # VM RAM size (Mb)
              :memory => 512,
              # networks
              :net => [],
              # forwarded ports
              :forwarded_port => []
            }
}


Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
#  config.vm.synced_folder "/home/user/sync", "/home/vagrant", disabled: true
  config.vm.box = "MrBrokenPC/centoshw1"
  config.vm.define boxname do |box|
end
end
end
