# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
    v.memory = 256
    v.cpus = 1
  end
  

  config.vm.define "hw16" do |hw16|
    hw16.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "nat"
    hw16.vm.hostname = "hw16"
    hw16.vm.provision "shell", path: "scriptshw16/script.sh"
  end


end
