# -*- mode: ruby -*-
# vi: set ft=ruby :
MACHINES = {
  # VM name "homework2"
  :"homework2" => {
              # VM box
              :box_name => "centosHW",
              # VM CPU count
              :cpus => 2,
              # VM RAM size (Mb)
              :memory => 1024,
              # networks
              :net => [],
              # forwarded ports
              :forwarded_port => [],
  	:disks => {
			:sata1 => {
				:dfile => './sata1.vdi',
				:size => 250,
				:port => 1
			},
			:sata2 => {
		                :dfile => './sata2.vdi',
		                :size => 250, 
				:port => 2
			},
		        :sata3 => {
		                :dfile => './sata3.vdi',
		                :size => 250,
		                :port => 3
		        },
		        :sata4 => {
		                :dfile => './sata4.vdi',
		                :size => 250, 
		                :port => 4
		        }
	     }
    },
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
  config.vm.synced_folder "/home/user/sync", "/home/vagrant", disabled: true
  config.vm.box = "centos/7"
  config.vm.define boxname do |box|
  config.vm.provision "raid", type: "shell", run: "once", path: "raid.sh"
          box.vm.provider :virtualbox do |vb|
                  needsController = false
		  boxconfig[:disks].each do |dname, dconf|
			  unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                needsController =  true
                          end

		  end
                  if needsController == true
                     vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
                  end
          end
 	  

end
end
end

