---
- hosts: inetRouter
  become: true
  tasks:
     - name: "Network configuration inetRouter"
       shell: "{{ item }}"
       with_items:
        - sysctl -w net.ipv4.ip_forward=1
        - ip route add 192.168.0.0/16 via 192.168.255.2
        - iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
- hosts: centralRouter
  become: true
  tasks:
     - name: "Network configuration centralRouter"
       shell: "{{ item }}"
       with_items:
        - sysctl -w net.ipv4.ip_forward=1
        - echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
        - ip route add 0.0.0.0/0 via 192.168.255.1
        - ip route add 192.168.1.0/24 via 192.168.255.10
        - ip route add 192.168.2.0/24 via 192.168.255.6
        - systemctl restart network
- hosts: centralServer
  become: true
  tasks:
     - name: "Network configuration centralServer"
       shell: "{{ item }}"
       with_items:
        - echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
        - ip route add 0.0.0.0/0 via 192.168.0.1
        - systemctl restart network
- hosts: office1Router
  become: true
  tasks:
     - name: "Network configuration office1Router"
       shell: "{{ item }}"
       with_items:
        - sysctl -w net.ipv4.ip_forward=1
        - echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
        - ip route add 0.0.0.0/0 via 192.168.255.5
        - systemctl restart network
- hosts: office1Server
  become: true
  tasks:
     - name: "Network configuration office1Server"
       shell: "{{ item }}"
       with_items:
        - echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
        - echo "DEFROUTE=yes" >> /etc/sysconfig/network-scripts/ifcfg-eth1
        - ip route add 0.0.0.0/0 via 192.168.2.65
        - systemctl restart network
- hosts: office2Router
  become: true
  tasks:
     - name: "Network configuration office2Router"
       shell: "{{ item }}"
       with_items:
        - sysctl -w net.ipv4.ip_forward=1
        - ip route add 0.0.0.0/0 via 192.168.255.9
        - systemctl restart network
- hosts: office2Server
  become: true
  tasks:
     - name: "Network configuration office2Server"
       shell: "{{ item }}"
       with_items:
        - echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
        - ip route add 0.0.0.0/0 via 192.168.1.129
        - systemctl restart network





































