---
- name: restart network
  systemd:
    name: network
    state: restarted

- name: stop server
  systemd:
    name: openvpn@server
    state: stopped
    enabled: no

- name: restart server
  systemd:
    name: openvpn@server
    state: restarted
    enabled: yes

- name: restart client
  systemd:
    name: openvpn@client
    state: restarted
    enabled: yes
