# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end

  config.vm.define "server" do |server|
    server.vm.network "private_network", ip: "192.168.10.10"
    server.vm.hostname = "server"
  end

  config.vm.define "client" do |client|
    client.vm.network "private_network", ip: "192.168.10.11"
    client.vm.hostname = "client"
  end

  config.vm.provision "openvpn", type:'ansible' do |ansible|
    ansible.inventory_path = './inventories/all.yml'
    ansible.playbook = './sts.yml'
  end
end
